using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace Mortz.Net.Gen;

[Generator]
public class ConfigCodecGenerator : IIncrementalGenerator
{
    private const string PREFIX = "Mortz.Core.Match.Configuration.";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, (output, compilation) =>
        {
            AttributeData? marker = compilation.Assembly.GetAttributes().FirstOrDefault(attribute =>
                attribute.AttributeClass?.ToDisplayString() == "Mortz.Protocol.Configuration.ConfigCodecsAttribute");
            if (marker?.ConstructorArguments.FirstOrDefault().Value is not INamedTypeSymbol root)
                return;
            HashSet<string> emitted = [];
            Emit(output, root, emitted);
        });
    }

    private static bool Has(IPropertySymbol property, string name) => property.GetAttributes()
        .Any(attribute => attribute.AttributeClass?.ToDisplayString() == PREFIX + name + "Attribute");

    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static string Codec(ITypeSymbol type) => TypeName(type) + "Codec";

    private static void Emit(SourceProductionContext output, INamedTypeSymbol type, HashSet<string> emitted)
    {
        if (!emitted.Add(TypeName(type)))
            return;
        IPropertySymbol[] fields = type.GetMembers().OfType<IPropertySymbol>()
            .Where(property => Has(property, "ConfigSection") || Has(property, "ConfigValue") ||
                Has(property, "PlayerStat") || Has(property, "MatchRule")).ToArray();
        AttributeData[] cases = type.GetAttributes().Where(attribute =>
            attribute.AttributeClass?.ToDisplayString() == PREFIX + "EndConditionCaseAttribute").ToArray();
        foreach (IPropertySymbol field in fields.Where(field => Has(field, "ConfigSection") || Has(field, "ConfigValue")))
        {
            Emit(output, (INamedTypeSymbol)field.Type, emitted);
        }
        foreach (AttributeData item in cases)
        {
            Emit(output, (INamedTypeSymbol)item.ConstructorArguments[2].Value!, emitted);
        }

        string name = TypeName(type);
        StringBuilder source = new($"// <auto-generated/>\n#nullable enable\nnamespace {type.ContainingNamespace};\npublic static class {type.Name}Codec\n{{\n");
        source.AppendLine($"    public static byte[] ToBytes(this {name} value)");
        source.AppendLine("    {\n        using global::System.IO.MemoryStream stream = new();\n        using global::System.IO.BinaryWriter writer = new(stream);");
        if (cases.Length > 0)
        {
            source.AppendLine("        switch (value)\n        {");
            foreach (AttributeData item in cases)
            {
                INamedTypeSymbol variant = (INamedTypeSymbol)item.ConstructorArguments[2].Value!;
                string id = SymbolDisplay.FormatLiteral((string)item.ConstructorArguments[0].Value!, true);
                source.AppendLine($"            case {TypeName(variant)} selected:\n            {{\n                writer.Write({id});\n                byte[] payload = {Codec(variant)}.ToBytes(selected);\n                writer.Write(payload.Length);\n                writer.Write(payload);\n                break;\n            }}");
            }
            source.AppendLine("            default: throw new global::System.NotSupportedException(value.GetType().Name);\n        }");
        }
        else if (fields.Any(field => Has(field, "ConfigSection")))
        {
            foreach (IPropertySymbol field in fields)
            {
                source.AppendLine($"        byte[] {field.Name} = {Codec(field.Type)}.ToBytes(value.{field.Name});\n        writer.Write({field.Name}.Length);\n        writer.Write({field.Name});");
            }
        }
        else
        {
            IPropertySymbol? nested = fields.SingleOrDefault(field => Has(field, "ConfigValue"));
            if (nested != null)
                source.AppendLine("        writer.Write(0); // Shared section length is filled after its fields.");
            foreach (IPropertySymbol field in fields.Where(field => !Has(field, "ConfigValue")))
            {
                source.AppendLine($"        writer.Write({(field.Type.TypeKind == TypeKind.Enum ? "(byte)" : "")}value.{field.Name});");
            }
            if (nested != null)
            {
                source.AppendLine("        int sharedLength = checked((int)stream.Position - 4);\n        stream.Position = 0;\n        writer.Write(sharedLength);\n        stream.Position = stream.Length;");
                source.AppendLine($"        writer.Write({Codec(nested.Type)}.ToBytes(value.{nested.Name}));");
            }
        }
        source.AppendLine("        return stream.ToArray();\n    }");
        source.AppendLine($"    public static {name} FromBytes(byte[] data)\n    {{\n        using global::System.IO.MemoryStream stream = new(data, writable: false);\n        using global::System.IO.BinaryReader reader = new(stream);");
        if (cases.Length > 0)
        {
            source.AppendLine("        string id = reader.ReadString();\n        byte[] payload = ReadSegment(reader);\n        if (stream.Position != stream.Length)\n            throw new global::System.IO.InvalidDataException(\"Trailing end-condition rule bytes.\");\n        return id switch\n        {");
            foreach (AttributeData item in cases)
            {
                string id = SymbolDisplay.FormatLiteral((string)item.ConstructorArguments[0].Value!, true);
                source.AppendLine($"            {id} => {Codec((ITypeSymbol)item.ConstructorArguments[2].Value!)}.FromBytes(payload),");
            }
            source.AppendLine("            _ => throw new global::System.IO.InvalidDataException(\"Unknown end-condition rules.\"),\n        };");
        }
        else
        {
            IPropertySymbol? nested = fields.SingleOrDefault(field => Has(field, "ConfigValue"));
            if (nested != null)
                source.AppendLine("        int sharedLength = reader.ReadInt32();\n        if (sharedLength < 0 || sharedLength > stream.Length - stream.Position)\n            throw new global::System.IO.InvalidDataException(\"Invalid shared configuration length.\");");
            source.AppendLine($"        {name} value = new()\n        {{");
            foreach (IPropertySymbol field in fields.Where(field => !Has(field, "ConfigValue")))
            {
                string expression = Has(field, "ConfigSection") ? $"{Codec(field.Type)}.FromBytes(ReadSegment(reader))" : Read(field.Type);
                source.AppendLine($"            {field.Name} = {expression},");
            }
            source.AppendLine("        };");
            if (nested != null)
            {
                source.AppendLine("        if (stream.Position != sharedLength + 4)\n            throw new global::System.IO.InvalidDataException(\"Invalid shared configuration length.\");");
                source.AppendLine($"        value.{nested.Name} = {Codec(nested.Type)}.FromBytes(reader.ReadBytes(checked((int)(stream.Length - stream.Position))));");
            }
            source.AppendLine("        if (stream.Position != stream.Length)\n            throw new global::System.IO.InvalidDataException(\"Trailing configuration bytes.\");\n        value.Clamp();\n        return value;");
        }
        source.AppendLine("    }");
        source.AppendLine("    private static byte[] ReadSegment(global::System.IO.BinaryReader reader)\n    {\n        int length = reader.ReadInt32();\n        if (length < 0 || length > reader.BaseStream.Length - reader.BaseStream.Position)\n            throw new global::System.IO.InvalidDataException(\"Invalid configuration segment length.\");\n        return reader.ReadBytes(length);\n    }");
        if (cases.Length == 0)
            source.AppendLine($"    public static byte[] ToBytes(this {name}Snapshot snapshot) => ToBytes(snapshot.ToMutable());");
        source.AppendLine("}");
        output.AddSource(type.Name + "Codec.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static string Read(ITypeSymbol type) => type.TypeKind == TypeKind.Enum
        ? $"({TypeName(type)})reader.ReadByte()"
        : type.SpecialType switch
        {
            SpecialType.System_Boolean => "reader.ReadBoolean()",
            SpecialType.System_Byte => "reader.ReadByte()",
            SpecialType.System_Int32 => "reader.ReadInt32()",
            SpecialType.System_Single => "reader.ReadSingle()",
            SpecialType.System_Double => "reader.ReadDouble()",
            SpecialType.System_String => "reader.ReadString()",
            _ => throw new InvalidOperationException($"Unsupported config wire type {type}"),
        };
}
