using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Mortz.Net.Gen;

[Generator]
public sealed class TomlModelGenerator : IIncrementalGenerator
{
    private const string MODEL = "Mortz.Content.TomlModelAttribute";

    private sealed record Root(INamedTypeSymbol Type);
    private sealed record ModelInfo(INamedTypeSymbol Type, IMethodSymbol? Constructor,
        ImmutableArray<FieldInfo> Fields, string? Discriminator, ImmutableArray<CaseInfo> Cases,
        ImmutableArray<MutableField> MutableFields = default);
    private sealed record FieldInfo(IParameterSymbol Parameter, IPropertySymbol Property,
        string Key, Shape Shape, bool Optional, string Default);
    private sealed record CaseInfo(string Name, INamedTypeSymbol Type);
    private sealed record MutableField(IPropertySymbol Property, string Key, Shape Shape,
        bool Required);
    private sealed record Shape(string Kind, ITypeSymbol Type, ITypeSymbol? Element = null);

    private static readonly DiagnosticDescriptor _unsupported = new("MZ4001", "Unsupported TOML model",
        "TOML member '{0}.{1}' has unsupported type '{2}'", "Mortz.Toml",
        DiagnosticSeverity.Error, true);
    private static readonly DiagnosticDescriptor _constructor = new("MZ4002", "Invalid TOML model",
        "TOML model '{0}' has no public constructor matching readable properties", "Mortz.Toml",
        DiagnosticSeverity.Error, true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<ImmutableArray<Root>> roots = context.SyntaxProvider
            .ForAttributeWithMetadataName(MODEL, static (node, _) => node is TypeDeclarationSyntax,
                static (ctx, _) => new Root((INamedTypeSymbol)ctx.TargetSymbol)).Collect();
        context.RegisterSourceOutput(roots, Emit);
    }

    private static void Emit(SourceProductionContext context, ImmutableArray<Root> roots)
    {
        if (roots.IsDefaultOrEmpty) return;
        Dictionary<INamedTypeSymbol, ModelInfo> models = new(SymbolEqualityComparer.Default);
        foreach (Root root in roots) Inspect(root.Type, models, context);
        ModelInfo[] ordered = models.Values.OrderBy(x => Name(x.Type), StringComparer.Ordinal).ToArray();
        if (ordered.Length == 0) return;

        StringBuilder b = new();
        b.AppendLine("// <auto-generated by Mortz.Net.Gen/>");
        b.AppendLine("#nullable enable");
        b.AppendLine("namespace Mortz.Content;");
        b.AppendLine("internal static class TomlGeneratedCode");
        b.AppendLine("{");
        EmitDispatch(b, ordered);
        for (int i = 0; i < ordered.Length; i++) EmitModel(b, ordered[i], i, ordered);
        b.AppendLine("}");
        context.AddSource("TomlGeneratedModels.g.cs", SourceText.From(b.ToString(), Encoding.UTF8));
    }

    private static void EmitDispatch(StringBuilder b, ModelInfo[] models)
    {
        b.AppendLine("    [global::System.Runtime.CompilerServices.ModuleInitializer]");
        b.AppendLine("    internal static void Register()");
        b.AppendLine("    {");
        for (int i = 0; i < models.Length; i++)
            b.AppendLine($"        TomlGeneratedModels.Register(typeof({TypeName(models[i].Type)}), (table, path, source, diagnostics) => Read{i}(table, path, source, diagnostics), value => Write{i}(({TypeName(models[i].Type)})value));");
        b.AppendLine("    }");
    }

    private static void EmitModel(StringBuilder b, ModelInfo model, int index, ModelInfo[] models)
    {
        if (model.Discriminator != null)
        {
            EmitUnion(b, model, index, models);
            return;
        }
        if (!model.MutableFields.IsDefaultOrEmpty)
        {
            EmitMutableModel(b, model, index, models);
            return;
        }
        string type = TypeName(model.Type);
        b.AppendLine($"    private static {type}? Read{index}(global::Tomlyn.Model.TomlTable table, string path, string source, global::System.Collections.Generic.List<ContentDiagnostic> diagnostics)");
        b.AppendLine("    {");
        b.Append("        TomlModel.UnknownKeys(table, new string[] { ")
            .Append(string.Join(", ", model.Fields.Select(x => Quote(x.Key)))).AppendLine(" }, path, source, diagnostics);");
        b.AppendLine("        bool ok = true;");
        for (int i = 0; i < model.Fields.Length; i++) EmitReadField(b, model.Fields[i], i, models);
        b.AppendLine("        if (!ok) return null;");
        b.Append($"        return new {type}(");
        b.Append(string.Join(", ", Enumerable.Range(0, model.Fields.Length).Select(i => $"v{i}")));
        b.AppendLine(");");
        b.AppendLine("    }");

        b.AppendLine($"    private static global::Tomlyn.Model.TomlTable Write{index}({type} value)");
        b.AppendLine("    {");
        b.AppendLine("        global::Tomlyn.Model.TomlTable table = new();");
        foreach (FieldInfo field in model.Fields) EmitWriteField(b, field, models);
        b.AppendLine("        return table;");
        b.AppendLine("    }");
    }

    private static void EmitMutableModel(StringBuilder b, ModelInfo model, int index,
        ModelInfo[] models)
    {
        string type = TypeName(model.Type);
        b.AppendLine($"    private static {type}? Read{index}(global::Tomlyn.Model.TomlTable table, string path, string source, global::System.Collections.Generic.List<ContentDiagnostic> diagnostics)");
        b.AppendLine("    {");
        b.Append("        TomlModel.UnknownKeys(table, new string[] { ")
            .Append(string.Join(", ", model.MutableFields.Select(x => Quote(x.Key))))
            .AppendLine(" }, path, source, diagnostics);");
        b.AppendLine($"        {type} defaults = new()");
        b.AppendLine("        {");
        foreach (MutableField field in model.MutableFields.Where(field => field.Required))
            b.AppendLine($"            {field.Property.Name} = default!,");
        b.AppendLine("        };");
        b.AppendLine("        bool ok = true;");
        for (int i = 0; i < model.MutableFields.Length; i++)
        {
            MutableField field = model.MutableFields[i];
            string fieldType = DeclaredTypeName(field.Property.Type);
            string effective = TypeName(field.Shape.Type);
            string fieldPath = $"TomlModel.Child(path, {Quote(field.Key)})";
            b.AppendLine($"        {fieldType} v{i} = defaults.{field.Property.Name};");
            string condition = field.Required
                ? $"TomlModel.Required(table, {Quote(field.Key)}, path, source, diagnostics, out object? r{i})"
                : $"table.TryGetValue({Quote(field.Key)}, out object? r{i})";
            b.AppendLine($"        if ({condition})");
            b.AppendLine("        {");
            if (field.Shape.Kind == "scalar")
                b.AppendLine($"            if (TomlModel.Scalar<{effective}>(r{i}, {fieldPath}, source, diagnostics, out {effective} x{i})) v{i} = x{i}; else ok = false;");
            else if (field.Shape.Kind is "scalar_array" or "model_array")
            {
                string element = TypeName(field.Shape.Element!);
                b.AppendLine($"            if (r{i} is global::System.Collections.IEnumerable sequence{i} && r{i} is not string)");
                b.AppendLine("            {");
                b.AppendLine($"                global::System.Collections.Generic.List<{element}> items{i} = new();");
                b.AppendLine($"                int n{i} = 0;");
                b.AppendLine($"                foreach (object? item{i} in sequence{i})");
                b.AppendLine("                {");
                string itemPath = $"$\"{{{fieldPath}}}[{{n{i}}}]\"";
                if (field.Shape.Kind == "scalar_array")
                    b.AppendLine($"                    if (TomlModel.Scalar<{element}>(item{i}, {itemPath}, source, diagnostics, out {element} x{i})) items{i}.Add(x{i}); else ok = false;");
                else
                {
                    int target = IndexOf(models, (INamedTypeSymbol)field.Shape.Element!);
                    b.AppendLine($"                    if (item{i} is global::Tomlyn.Model.TomlTable t{i} && Read{target}(t{i}, {itemPath}, source, diagnostics) is {element} x{i}) items{i}.Add(x{i}); else ok = false;");
                }
                b.AppendLine($"                    n{i}++;");
                b.AppendLine("                }");
                b.AppendLine($"                v{i} = items{i}.ToArray();");
                b.AppendLine("            }");
                b.AppendLine($"            else {{ TomlModel.Error(diagnostics, source, $\"'{{{fieldPath}}}' must be an array\"); ok = false; }}");
            }
            else
            {
                int target = IndexOf(models, (INamedTypeSymbol)field.Shape.Type);
                b.AppendLine($"            if (r{i} is global::Tomlyn.Model.TomlTable t{i} && Read{target}(t{i}, {fieldPath}, source, diagnostics) is {effective} x{i}) v{i} = x{i}; else {{ if (r{i} is not global::Tomlyn.Model.TomlTable) TomlModel.Error(diagnostics, source, $\"'{{{fieldPath}}}' must be a table\"); ok = false; }}");
            }
            b.AppendLine("        }");
            if (field.Required) b.AppendLine("        else ok = false;");
        }
        b.AppendLine("        if (!ok) return null;");
        b.AppendLine($"        return new {type}");
        b.AppendLine("        {");
        for (int i = 0; i < model.MutableFields.Length; i++)
            b.AppendLine($"            {model.MutableFields[i].Property.Name} = v{i},");
        b.AppendLine("        };");
        b.AppendLine("    }");
        b.AppendLine($"    private static global::Tomlyn.Model.TomlTable Write{index}({type} value)");
        b.AppendLine("    {");
        b.AppendLine("        global::Tomlyn.Model.TomlTable table = new();");
        foreach (MutableField field in model.MutableFields)
        {
            string property = $"value.{field.Property.Name}";
            bool nullable = field.Property.Type.NullableAnnotation == NullableAnnotation.Annotated ||
                IsNullableValue(field.Property.Type);
            string local = "present" + field.Property.Name;
            string guard = nullable ? $"if ({property} is {{ }} {local}) " : "";
            string value = nullable ? local : property;
            if (field.Shape.Kind == "scalar")
                b.AppendLine($"        {guard}table[{Quote(field.Key)}] = TomlModel.WriteScalar({value});");
            else if (field.Shape.Kind is "scalar_array" or "model_array")
            {
                bool scalar = field.Shape.Kind == "scalar_array";
                string collection = scalar ? "global::Tomlyn.Model.TomlArray" : "global::Tomlyn.Model.TomlTableArray";
                string item = scalar ? "TomlModel.WriteScalar(item!)"
                    : $"Write{IndexOf(models, (INamedTypeSymbol)field.Shape.Element!)}(item!)";
                b.AppendLine($"        {guard}{{ {collection} items = new(); foreach (var item in {value}) items.Add({item}); table[{Quote(field.Key)}] = items; }}");
            }
            else
                b.AppendLine($"        {guard}table[{Quote(field.Key)}] = Write{IndexOf(models, (INamedTypeSymbol)field.Shape.Type)}({value});");
        }
        b.AppendLine("        return table;");
        b.AppendLine("    }");
    }

    private static void EmitUnion(StringBuilder b, ModelInfo model, int index, ModelInfo[] models)
    {
        string type = TypeName(model.Type);
        string discriminator = model.Discriminator!;
        b.AppendLine($"    private static {type}? Read{index}(global::Tomlyn.Model.TomlTable table, string path, string source, global::System.Collections.Generic.List<ContentDiagnostic> diagnostics)");
        b.AppendLine("    {");
        b.AppendLine($"        if (!TomlModel.Required(table, {Quote(discriminator)}, path, source, diagnostics, out object? raw) || !TomlModel.Scalar<string>(raw, TomlModel.Child(path, {Quote(discriminator)}), source, diagnostics, out string tag)) return null;");
        b.AppendLine("        return tag switch");
        b.AppendLine("        {");
        foreach (CaseInfo item in model.Cases)
        {
            int target = IndexOf(models, item.Type);
            b.AppendLine($"            {Quote(item.Name)} => Read{target}(Without(table, {Quote(discriminator)}), path, source, diagnostics),");
        }
        b.AppendLine("            _ => BadTag(),");
        b.AppendLine("        };");
        b.AppendLine($"        {type}? BadTag() {{ TomlModel.Error(diagnostics, source, $\"'{{TomlModel.Child(path, {Quote(discriminator)})}}' has unknown type '{{tag}}'\"); return null; }}");
        b.AppendLine("    }");
        b.AppendLine($"    private static global::Tomlyn.Model.TomlTable Write{index}({type} value)");
        b.AppendLine("    {");
        b.AppendLine("        global::Tomlyn.Model.TomlTable table;");
        b.AppendLine("        string tag;");
        b.AppendLine("        switch (value)");
        b.AppendLine("        {");
        foreach (CaseInfo item in model.Cases)
        {
            int target = IndexOf(models, item.Type);
            b.AppendLine($"            case {TypeName(item.Type)} item: table = Write{target}(item); tag = {Quote(item.Name)}; break;");
        }
        b.AppendLine("            default: throw new global::System.NotSupportedException($\"unknown TOML union member '{value.GetType().Name}'\");");
        b.AppendLine("        }");
        b.AppendLine($"        global::Tomlyn.Model.TomlTable result = new() {{ [{Quote(discriminator)}] = tag }};");
        b.AppendLine("        foreach (var pair in table) result.Add(pair.Key, pair.Value);");
        b.AppendLine("        return result;");
        b.AppendLine("    }");
        b.AppendLine("    private static global::Tomlyn.Model.TomlTable Without(global::Tomlyn.Model.TomlTable source, string key) { global::Tomlyn.Model.TomlTable copy = new(); foreach (var pair in source) if (pair.Key != key) copy.Add(pair.Key, pair.Value); return copy; }");
    }

    private static void EmitReadField(StringBuilder b, FieldInfo field, int i, ModelInfo[] models)
    {
        string declared = TypeName(field.Parameter.Type);
        string effective = TypeName(field.Shape.Type);
        string path = $"TomlModel.Child(path, {Quote(field.Key)})";
        b.AppendLine($"        {declared} v{i} = {field.Default};");
        string condition = field.Optional
            ? $"table.TryGetValue({Quote(field.Key)}, out object? r{i})"
            : $"TomlModel.Required(table, {Quote(field.Key)}, path, source, diagnostics, out object? r{i})";
        b.AppendLine($"        if ({condition})");
        b.AppendLine("        {");
        if (field.Shape.Kind == "scalar")
            b.AppendLine($"            if (TomlModel.Scalar<{effective}>(r{i}, {path}, source, diagnostics, out {effective} x{i})) v{i} = x{i}; else ok = false;");
        else if (field.Shape.Kind == "model")
        {
            int target = IndexOf(models, (INamedTypeSymbol)field.Shape.Type);
            b.AppendLine($"            if (r{i} is global::Tomlyn.Model.TomlTable t{i} && Read{target}(t{i}, {path}, source, diagnostics) is {effective} x{i}) v{i} = x{i}; else {{ if (r{i} is not global::Tomlyn.Model.TomlTable) TomlModel.Error(diagnostics, source, $\"'{{{path}}}' must be a table\"); ok = false; }}");
        }
        else EmitReadArray(b, field, i, path, models);
        b.AppendLine("        }");
        if (!field.Optional) b.AppendLine("        else ok = false;");
    }

    private static void EmitReadArray(StringBuilder b, FieldInfo field, int i, string path, ModelInfo[] models)
    {
        string element = TypeName(field.Shape.Element!);
        b.AppendLine($"            if (r{i} is global::System.Collections.IEnumerable sequence{i} && r{i} is not string)");
        b.AppendLine("            {");
        b.AppendLine($"                global::System.Collections.Generic.List<{element}> a{i} = new();");
        b.AppendLine($"                int n{i} = 0;");
        b.AppendLine($"                foreach (object? item{i} in sequence{i})");
        b.AppendLine("                {");
        string itemPath = $"$\"{{{path}}}[{{n{i}}}]\"";
        if (field.Shape.Kind == "scalar_array")
            b.AppendLine($"                    if (TomlModel.Scalar<{element}>(item{i}, {itemPath}, source, diagnostics, out {element} x{i})) a{i}.Add(x{i}); else ok = false;");
        else
        {
            int target = IndexOf(models, (INamedTypeSymbol)field.Shape.Element!);
            b.AppendLine($"                    if (item{i} is global::Tomlyn.Model.TomlTable t{i} && Read{target}(t{i}, {itemPath}, source, diagnostics) is {element} x{i}) a{i}.Add(x{i}); else {{ if (item{i} is not global::Tomlyn.Model.TomlTable) TomlModel.Error(diagnostics, source, $\"'{{{itemPath}}}' must be a table\"); ok = false; }}");
        }
        b.AppendLine($"                    n{i}++;");
        b.AppendLine("                }");
        b.AppendLine($"                v{i} = a{i}.ToArray();");
        b.AppendLine("            }");
        b.AppendLine($"            else {{ TomlModel.Error(diagnostics, source, $\"'{{{path}}}' must be an array\"); ok = false; }}");
    }

    private static void EmitWriteField(StringBuilder b, FieldInfo field, ModelInfo[] models)
    {
        string property = $"value.{field.Property.Name}";
        bool nullable = field.Parameter.Type.IsReferenceType || IsNullableValue(field.Parameter.Type);
        string local = "present" + field.Property.Name;
        string guard = field.Optional && nullable ? $"if ({property} is {{ }} {local}) " : "";
        string value = field.Optional && nullable ? local : property;
        if (field.Shape.Kind == "scalar")
            b.AppendLine($"        {guard}table[{Quote(field.Key)}] = TomlModel.WriteScalar({value});");
        else if (field.Shape.Kind == "model")
        {
            int target = IndexOf(models, (INamedTypeSymbol)field.Shape.Type);
            b.AppendLine($"        {guard}table[{Quote(field.Key)}] = Write{target}({value});");
        }
        else
        {
            bool scalar = field.Shape.Kind == "scalar_array";
            string collection = scalar ? "global::Tomlyn.Model.TomlArray" : "global::Tomlyn.Model.TomlTableArray";
            b.AppendLine($"        {guard}{{ {collection} items = new(); foreach (var item in {value}) items.Add({(scalar ? "TomlModel.WriteScalar(item!)" : $"Write{IndexOf(models, (INamedTypeSymbol)field.Shape.Element!)}(item!)")}); table[{Quote(field.Key)}] = items; }}");
        }
    }

    private static void Inspect(INamedTypeSymbol type, Dictionary<INamedTypeSymbol, ModelInfo> models,
        SourceProductionContext context)
    {
        if (models.ContainsKey(type)) return;
        AttributeData? union = Attr(type, "TomlUnionAttribute");
        if (union != null)
        {
            ImmutableArray<CaseInfo>.Builder cases = ImmutableArray.CreateBuilder<CaseInfo>();
            string discriminator = union.ConstructorArguments.Length == 0
                ? "type"
                : (string?)union.ConstructorArguments[0].Value ?? "type";
            models[type] = new(type, null, ImmutableArray<FieldInfo>.Empty, discriminator,
                ImmutableArray<CaseInfo>.Empty);
            foreach (AttributeData attr in type.GetAttributes().Where(x => x.AttributeClass?.Name == "TomlCaseAttribute"))
            {
                if (attr.ConstructorArguments.Length == 2 &&
                    attr.ConstructorArguments[0].Value is string name &&
                    attr.ConstructorArguments[1].Value is INamedTypeSymbol member)
                {
                    cases.Add(new(name, member));
                    Inspect(member, models, context);
                }
            }
            models[type] = new(type, null, ImmutableArray<FieldInfo>.Empty, discriminator,
                cases.ToImmutable());
            return;
        }
        IMethodSymbol? ctor = type.InstanceConstructors.Where(x => x.DeclaredAccessibility == Accessibility.Public)
            .OrderByDescending(x => x.Parameters.Length).FirstOrDefault(x => x.Parameters.All(p => FindProperty(type, p.Name) != null));
        if (ctor == null) { context.ReportDiagnostic(Diagnostic.Create(_constructor, type.Locations.FirstOrDefault(), Name(type))); return; }
        if (ctor.Parameters.Length == 0)
        {
            IPropertySymbol[] properties = type.GetMembers().OfType<IPropertySymbol>()
                .Where(property => property.DeclaredAccessibility == Accessibility.Public &&
                    property.SetMethod?.DeclaredAccessibility == Accessibility.Public &&
                    Attr(property, "TomlIgnoreAttribute") == null)
                .ToArray();
            if (properties.Length > 0)
            {
                models[type] = new(type, ctor, ImmutableArray<FieldInfo>.Empty, null,
                    ImmutableArray<CaseInfo>.Empty, ImmutableArray<MutableField>.Empty);
                ImmutableArray<MutableField>.Builder mutable = ImmutableArray.CreateBuilder<MutableField>();
                foreach (IPropertySymbol property in properties)
                {
                    ITypeSymbol effective = Unwrap(property.Type);
                    Shape? shape = ShapeOf(effective);
                    if (shape == null)
                    {
                        context.ReportDiagnostic(Diagnostic.Create(_unsupported,
                            property.Locations.FirstOrDefault(), Name(type), property.Name, property.Type));
                        continue;
                    }
                    string key = (string?)Attr(property, "TomlNameAttribute")?.ConstructorArguments[0].Value
                        ?? Snake(property.Name);
                    mutable.Add(new(property, key, shape, property.IsRequired));
                    if (shape.Kind == "model") Inspect((INamedTypeSymbol)shape.Type, models, context);
                    if (shape.Kind == "model_array") Inspect((INamedTypeSymbol)shape.Element!, models, context);
                }
                models[type] = new(type, ctor, ImmutableArray<FieldInfo>.Empty, null,
                    ImmutableArray<CaseInfo>.Empty, mutable.ToImmutable());
                return;
            }
        }
        models[type] = new(type, ctor, ImmutableArray<FieldInfo>.Empty, null,
            ImmutableArray<CaseInfo>.Empty);
        ImmutableArray<FieldInfo>.Builder fields = ImmutableArray.CreateBuilder<FieldInfo>();
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            IPropertySymbol property = FindProperty(type, parameter.Name)!;
            ITypeSymbol effective = Unwrap(parameter.Type);
            Shape? shape = ShapeOf(effective);
            if (shape == null) { context.ReportDiagnostic(Diagnostic.Create(_unsupported, parameter.Locations.FirstOrDefault(), Name(type), parameter.Name, parameter.Type)); continue; }
            string key = (string?)Attr(parameter, property, "TomlNameAttribute")?.ConstructorArguments[0].Value ?? Snake(parameter.Name);
            bool optional = parameter.HasExplicitDefaultValue || parameter.Type.NullableAnnotation == NullableAnnotation.Annotated || IsNullableValue(parameter.Type);
            fields.Add(new(parameter, property, key, shape, optional, Default(parameter, shape, optional)));
            if (shape.Kind == "model") Inspect((INamedTypeSymbol)shape.Type, models, context);
            if (shape.Kind == "model_array") Inspect((INamedTypeSymbol)shape.Element!, models, context);
        }
        models[type] = new(type, ctor, fields.ToImmutable(), null, ImmutableArray<CaseInfo>.Empty);
    }

    private static Shape? ShapeOf(ITypeSymbol type)
    {
        if (IsScalar(type)) return new("scalar", type);
        if (type is IArrayTypeSymbol { Rank: 1 } array)
            return new(IsScalar(array.ElementType) ? "scalar_array" : "model_array",
                type, array.ElementType);
        return type is INamedTypeSymbol ? new("model", type) : null;
    }
    private static bool IsScalar(ITypeSymbol type) => type.TypeKind == TypeKind.Enum || type.SpecialType is
        SpecialType.System_Boolean or SpecialType.System_Int32 or SpecialType.System_Int64 or
        SpecialType.System_Single or SpecialType.System_Double or SpecialType.System_String;
    private static ITypeSymbol Unwrap(ITypeSymbol type) => type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } n ? n.TypeArguments[0] : type;
    private static bool IsNullableValue(ITypeSymbol type) => type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T };
    private static string Default(IParameterSymbol p, Shape shape, bool optional)
    {
        if (p.HasExplicitDefaultValue && p.ExplicitDefaultValue == null &&
            p.Type.NullableAnnotation == NullableAnnotation.Annotated)
            return "null";
        if (shape.Kind.EndsWith("array", StringComparison.Ordinal))
            return "global::System.Array.Empty<" + TypeName(shape.Element!) + ">()";
        if (p.HasExplicitDefaultValue) return p.ExplicitDefaultValue switch
        {
            null => "null",
            string s => Quote(s),
            bool b => b ? "true" : "false",
            float f => f.ToString("R", System.Globalization.CultureInfo.InvariantCulture) + "f",
            double d => d.ToString("R", System.Globalization.CultureInfo.InvariantCulture),
            long l => l.ToString(System.Globalization.CultureInfo.InvariantCulture) + "L",
            _ => Convert.ToString(p.ExplicitDefaultValue, System.Globalization.CultureInfo.InvariantCulture) ?? "default"
        };
        if (optional) return "default";
        return "default!";
    }
    private static IPropertySymbol? FindProperty(INamedTypeSymbol type, string name)
    {
        for (INamedTypeSymbol? current = type; current != null; current = current.BaseType)
        {
            IPropertySymbol? property = current.GetMembers().OfType<IPropertySymbol>()
                .FirstOrDefault(x => x.GetMethod != null &&
                    string.Equals(x.Name, name, StringComparison.OrdinalIgnoreCase));
            if (property != null) return property;
        }
        return null;
    }
    private static AttributeData? Attr(INamedTypeSymbol type, string name) => type.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == name);
    private static AttributeData? Attr(IPropertySymbol property, string name) =>
        property.GetAttributes().FirstOrDefault(x => x.AttributeClass?.Name == name);
    private static AttributeData? Attr(IParameterSymbol p, IPropertySymbol property, string name) => p.GetAttributes().Concat(property.GetAttributes()).FirstOrDefault(x => x.AttributeClass?.Name == name);
    private static int IndexOf(ModelInfo[] models, INamedTypeSymbol type) => Array.FindIndex(models, x => SymbolEqualityComparer.Default.Equals(x.Type, type));
    private static string TypeName(ITypeSymbol type) => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    private static string DeclaredTypeName(ITypeSymbol type) => TypeName(type) +
        (type.IsReferenceType && type.NullableAnnotation == NullableAnnotation.Annotated ? "?" : "");
    private static string Name(INamedTypeSymbol type) => type.ToDisplayString();
    private static string Quote(string value) => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, true);
    private static string Snake(string name)
    {
        StringBuilder b = new();
        for (int i = 0; i < name.Length; i++) { char c = name[i]; if (char.IsUpper(c) && i > 0 && name[i - 1] != '_' && (!char.IsUpper(name[i - 1]) || i + 1 < name.Length && char.IsLower(name[i + 1]))) b.Append('_'); b.Append(char.ToLowerInvariant(c)); }
        return b.ToString();
    }
}
