name = "brt garden"
suggested_players = 2
[[spawn_points]]
x = 78
y = 604
team = "blue"
[[spawn_points]]
x = 171
y = 603
team = "blue"
[[spawn_points]]
x = 1092
y = 591
team = "red"
[[spawn_points]]
x = 1187
y = 591
team = "red"
