<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <NoWarn>$(NoWarn);EnableGenerateDocumentationFile</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mortz.Core\Mortz.Core.csproj" />
  </ItemGroup>
</Project>
